name: SwiftShader

on:
  push:
    branches:
      - rc/**
      - pr/**

jobs:
  swiftshader:
    name: Test Filament + Vulkan + SwiftShader
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2.0.0

    # This PAT only has `read:packages` enabled, and is saved as an Actions secret.
    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Download Image with Pre-Built SwiftShader
      run: |
          docker pull ghcr.io/prideout/filamentss.latest
          docker tag ghcr.io/prideout/filamentss.latest ssfilament

    - name: Build Filament with SwiftShader Support
      run: |
          docker run -v `pwd`:/trees/branch ssfilament branch/build.sh -t release

    - name: Test Filament
      continue-on-error: true
      timeout-minutes: 5
      run: |
          export SPEC=/trees/branch/libs/viewer/tests/basic.json
          export TEST=/trees/branch/out/cmake-release/samples/gltf_viewer
          mkdir results
          echo Starting Filament...

          # The hope behind --cpus and -t is to alleviate delays in GitHub's real-time log output.
          docker run --cpus="1.5" -tv `pwd`:/trees/branch -w /trees/branch/results ssfilament $TEST --batch $SPEC --headless -a vulkan

    # The results folder contains screenshots and settings files. If a segfault occurs, a core dump
    # will also be available in the results folder.
    - uses: actions/upload-artifact@v2
      with:
        name: results
        path: results
